# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: gemini:gemini-2.5-flash
clients:
- type: gemini
  api_key: 

stream: true                     # Controls whether to use the stream-style API.
save: true                       # Indicates whether to persist the message
keybindings: vi                  # Choose keybinding style (emacs, vi)
wrap: auto                         # Controls text wrapping (no, auto, <max-width>)
wrap_code: false                 # Enables or disables wrapping of code blocks

# Controls the persistence of the session. if true, auto save; if false, not save; if null, asking the user
save_session: true
# Compress session when token count reaches or exceeds this threshold
compress_threshold: 4000
# Text prompt used for creating a concise summary of session message
#summarize_prompt: '...'
# Text prompt used for including the summary of the entire session
summary_prompt: '...'
